[alias]
fmt-check        = "fmt --all -- --check"
integration-test = "test --test integration"
lint             = "clippy -- -D warnings"
schema           = "run schema"
wasm             = "build --release --lib --target wasm32-unknown-unknown --locked"
wasm-debug       = "build --lib --target wasm32-unknown-unknown --locked"

[target.wasm32-unknown-unknown]
rustflags = ["-C", "link-arg=-s"]
